In [16]:
import numpy as np

In [17]:
a = np.array(5)

In [18]:
a.ndim

0

In [19]:
a.shape

()

In [20]:
x = np.array([1, 2, 3])

In [21]:

x.shape

(3,)

In [22]:
x.ndim

1

In [23]:
y = np.array([[4],
              [5],
              [6]])

In [24]:
y.ndim

2

In [25]:
y.shape

(3, 1)

In [26]:
x.reshape((-1, 1))

array([[1],
       [2],
       [3]])

In [27]:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [28]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

In [29]:
x @ y


np.int64(44)

In [30]:
np.linalg.norm(x)


np.float64(7.483314773547883)

In [31]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [32]:
B = np.zeros((3, 3))
C = np. ones((2,))

In [33]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
A = np.diag([1, 1, 1])

In [35]:
A = np.array([[0, 1],
              [-1, 0]])